import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
const page = await ctx.newPage();
await page.goto('http://localhost:4321/join', { waitUntil: 'networkidle' });
await page.waitForTimeout(1500);
await page.screenshot({ path: '/tmp/join-1.png', fullPage: false });
await page.evaluate(() => window.scrollTo(0, 900));
await page.waitForTimeout(400);
await page.screenshot({ path: '/tmp/join-2.png', fullPage: false });
await page.evaluate(() => window.scrollTo(0, 1800));
await page.waitForTimeout(400);
await page.screenshot({ path: '/tmp/join-3.png', fullPage: false });
await page.evaluate(() => window.scrollTo(0, 2700));
await page.waitForTimeout(400);
await page.screenshot({ path: '/tmp/join-4.png', fullPage: false });
await page.evaluate(() => window.scrollTo(0, 3600));
await page.waitForTimeout(400);
await page.screenshot({ path: '/tmp/join-5.png', fullPage: false });
await browser.close();
console.log('done');
