// Convert the raw Cedar Grove captures into 1920px-wide webp assets.
//
// 1920 wide is not arbitrary: it is what the page declares, so the browser
// reserves the right box before the file arrives. The captures come off a
// deviceScaleFactor of 2, so each is halved here rather than upscaled.
import sharp from 'sharp';
import { readdirSync, mkdirSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, basename } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, 'raw-grove');
const out = join(here, '..', '..', 'public', 'app');
mkdirSync(out, { recursive: true });

// The page needs the frame's intrinsic size to reserve each box before the
// image arrives. That number was typed into the page, and the first time the
// captures changed shape (the rail collapsed) all five went stale at once,
// which is a layout shift on every row. It is written here instead, from the
// files that were actually produced, and the page imports it.
//
// One frame for all of them, and this asserts it rather than trusting it. The
// page is composed against a single aspect now; a capture that came back a
// different shape would put the scrapbook back one row at a time, silently.
const sizes = {};

// What the page shows, which is not everything the capture script takes.
//
// capture-grove.mjs walks all five surfaces, because the frame it captures at
// is how the product is held to one screenful per surface; that check is worth
// running on Projects and Library whether or not they appear on the page. The
// page itself is three acts (see the note over GROVE_TOUR in cedar-grove.astro),
// so publishing all five put 323KB of files in public/app that nothing linked.
const PUBLISHED = new Set([
  'grove-home',
  'grove-home-dark',
  'grove-explore',
  'grove-explore-dark',
  'grove-outputs',
  'grove-outputs-dark',
]);

for (const f of readdirSync(src).filter((f) => f.endsWith('.png'))) {
  const name = basename(f, '.png');
  if (!PUBLISHED.has(name)) {
    // A surface that used to ship and no longer does leaves its file behind
    // otherwise, and a stale capture on disk outlives every reason it existed.
    const stale = join(out, `${name}.webp`);
    if (existsSync(stale)) rmSync(stale);
    console.log(`${name}  captured, not published`);
    continue;
  }
  const meta = await sharp(join(src, f)).metadata();
  const info = await sharp(join(src, f))
    .resize({ width: 1920 })
    .webp({ quality: 90 })
    .toFile(join(out, `${name}.webp`));
  sizes[name] = { width: info.width, height: info.height };
  console.log(`${name}.webp  ${info.width}x${info.height}  from ${meta.width}x${meta.height}`);
}

const shapes = new Set(Object.values(sizes).map((s) => `${s.width}x${s.height}`));
if (shapes.size !== 1) {
  const listed = Object.entries(sizes)
    .map(([name, s]) => `${name} ${s.width}x${s.height}`)
    .join(', ');
  throw new Error(
    `optimize-grove: the captures are not one frame (${listed}). ` +
      'Re-run capture-grove.mjs; do not publish a page of mixed shapes.',
  );
}
const [first] = Object.values(sizes);
const manifest = join(here, '..', '..', 'src', 'data', 'groveShots.generated.json');
writeFileSync(
  manifest,
  `${JSON.stringify(
    {
      '//': 'Generated by scripts/screenshots/optimize-grove.mjs. Do not hand-edit.',
      frame: { width: first.width, height: first.height },
      shots: Object.keys(sizes).sort(),
    },
    null,
    2,
  )}\n`,
);
console.log(
  `wrote frame ${first.width}x${first.height} for ${Object.keys(sizes).length} shots to src/data/groveShots.generated.json`,
);
