// Convert the raw Cedar Grove captures into 1920px-wide webp assets.
//
// 1920 wide is not arbitrary: it is what the page declares, so the browser
// reserves the right box before the file arrives. The captures come off a
// deviceScaleFactor of 2, so each is halved here rather than upscaled.
import sharp from 'sharp';
import { readdirSync, mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, basename } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, 'raw-grove');
const out = join(here, '..', '..', 'public', 'app');
mkdirSync(out, { recursive: true });

// The page needs each file's intrinsic height to reserve its box before the
// image arrives. Those numbers were typed into the page, and the first time the
// captures changed shape (the rail collapsed) all five went stale at once, which
// is a layout shift on every row. They are written here instead, from the files
// that were actually produced, and the page imports them.
const sizes = {};

for (const f of readdirSync(src).filter((f) => f.endsWith('.png'))) {
  const name = basename(f, '.png');
  const meta = await sharp(join(src, f)).metadata();
  const info = await sharp(join(src, f))
    .resize({ width: 1920 })
    .webp({ quality: 90 })
    .toFile(join(out, `${name}.webp`));
  sizes[name] = { width: info.width, height: info.height };
  console.log(`${name}.webp  ${info.width}x${info.height}  from ${meta.width}x${meta.height}`);
}

const manifest = join(here, '..', '..', 'src', 'data', 'groveShots.generated.json');
writeFileSync(
  manifest,
  `${JSON.stringify({ '//': 'Generated by scripts/screenshots/optimize-grove.mjs. Do not hand-edit.', sizes }, null, 2)}\n`,
);
console.log(`wrote ${Object.keys(sizes).length} sizes to src/data/groveShots.generated.json`);
